name: socialpixel
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Curent App state management solution
  flutter_bloc: any
  # Color package add more functionality
  tinycolor: ^1.0.3
  camera: ^0.6.0
  # Used for path generating functions for the images captured
  path:
  path_provider:
  # Image cropper that has both cropping and rotating functionailty
  image_cropper: ^1.3.1
  # imagelibrary providing more control of images
  image: ^2.1.19
  # Fixes Rotation
  flutter_exif_rotation: ^0.3.2
  # Allows reading the metadata of the picture
  exif: ^1.0.3
  photofilters: ^2.0.1
  # Geolocation detection
  geolocator: ^6.1.14
  # Date and time format and usage
  intl: ^0.16.1
  # image picker for flutter
  image_picker: ^0.6.7+21
  # map for flutter
  flutter_map: ^0.10.1+1
  # google maps for flutter
  google_maps_flutter: ^1.1.1
  # http
  http: ^0.12.2
  # hive database for caching
  hive:
  hive_flutter:
  # tflite
  tflite: ^1.1.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  geocoding:

dev_dependencies:
  english_words: ^3.1.5
  hive_generator:
  build_runner:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.jpg
    - assets/images/pin.png
    - assets/images/default_profile.jpg
    - assets/images/grey.jpg
    - assets/tflite/ssd_mobilenet.tflite
    - assets/tflite/labels.txt
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Circular
      fonts:
        - asset: fonts/CircularStd-Book.ttf
          weight: 400
        - asset: fonts/CircularStd-Medium.ttf
          weight: 600
        - asset: fonts/CircularStd-Bold.ttf
          weight: 800
        - asset: fonts/CircularStd-Black.ttf
          weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
